Build a regression model.

In [4]:
import statsmodels.api as sm
import pandas as pd
import numpy as np
import os

In [6]:
#import Joined Data into new dataframe 
df = pd.read_csv('../data/JoinedData.csv')
df['Contact#'] = df['Contact#'].astype(str).str[:10]  # fix contact# format
df

,available_bikes,longitude,latitude,name,rating,pricing,review_count,street address,Is Closed,Contact#
0,3,-79.88,43.26,La Luna,3.8,2.0,66,306 King Street W,False,1905577023
1,3,-79.88,43.26,Pho Nhung,4.4,NaN,18,85 Queen St N,False,1905525800
2,3,-79.88,43.26,The Coop,3.8,2.0,43,274-274 King Street W,False,1289778266
3,3,-79.88,43.26,Ark and Anchor,4.3,2.0,14,300 King Street W,False,1905751934
4,3,-79.88,43.26,Moodys,3.8,NaN,14,107 George Street,False,1289309644
...,...,...,...,...,...,...,...,...,...,...
20149,1,-79.82,43.25,Boardwalk Cheesesteaks,4.5,NaN,4,131 Ottawa Street North,False,1905393177
20150,1,-79.82,43.25,Simply Italian Bakery,4.5,NaN,2,212 Ottawa Street N,False,1905592163
20151,1,-79.82,43.25,The Parlour Dairy Bar,4.5,NaN,2,224 Ottawa St N,False,1289389555
20152,1,-79.82,43.25,Mike's Subs,3.8,1.0,9,122 Ottawa Street N,False,1905544718
20153,1,-79.82,43.25,Crown & Press,5.0,NaN,1,303 Ottawa Street N,False,1905543012

In [9]:
# Selecting relevant columns for the regression model
features = ['rating', 'pricing', 'review_count']
target = 'available_bikes'

# Preprocessing the data: handling missing values
df = df[features + [target]].dropna()

# Splitting the data into training and testing sets (placeholder method)
train_df = df.sample(frac=0.8, random_state=0)  # 80% of the data for training
test_df = df.drop(train_df.index)  # the remaining 20% for testing


# Adding a constant to the model (intercept)
X_train = sm.add_constant(train_df[features])
y_train = train_df[target]
X_test = sm.add_constant(test_df[features])
y_test = test_df[target]

# Build the OLS model
model = sm.OLS(y_train, X_train)

# Fit the model
results = model.fit()

Provide model output and an interpretation of the results.

In [10]:
# Print out the statistics
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:        available_bikes   R-squared:                       0.018
Model:                            OLS   Adj. R-squared:                  0.018
Method:                 Least Squares   F-statistic:                     68.17
Date:                Tue, 16 Apr 2024   Prob (F-statistic):           1.12e-43
Time:                        22:09:35   Log-Likelihood:                -34583.
No. Observations:               11248   AIC:                         6.917e+04
Df Residuals:                   11244   BIC:                         6.920e+04
Df Model:                           3
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const           10.4110      0.378     27.576      0.000       9.671      11.151
rating          -0.9377      0.091    -10.280      0.000      -1.117      -0.759
pricing         -0.3946      0.082     -4.802      0.000      -0.556      -0.234
review_count    -0.0043      0.001     -4.873      0.000      -0.006      -0.003
==============================================================================
Omnibus:                     3666.449   Durbin-Watson:                   1.976
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            11763.085
Skew:                           1.676   Prob(JB):                         0.00
Kurtosis:                       6.723   Cond. No.                         657.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

# Stretch

How can you turn the regression model into a classification model?